// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "description": "Authenticate user and return JWT token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "User login",
                "parameters": [
                    {
                        "description": "Login credentials",
                        "name": "credentials",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_HSI-Sandbox-Golang-Team-2025_Team-2_pkg_auth.LoginBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Login success!",
                        "schema": {
                            "$ref": "#/definitions/github_com_HSI-Sandbox-Golang-Team-2025_Team-2_pkg_auth.SuccessLoginResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid credentials!",
                        "schema": {
                            "$ref": "#/definitions/github_com_HSI-Sandbox-Golang-Team-2025_Team-2_pkg_auth.InvalidLoginResponse"
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "description": "Register a user and return JWT token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "User register",
                "parameters": [
                    {
                        "description": "New user data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_HSI-Sandbox-Golang-Team-2025_Team-2_pkg_auth.RegisterBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Registration success!",
                        "schema": {
                            "$ref": "#/definitions/github_com_HSI-Sandbox-Golang-Team-2025_Team-2_pkg_auth.SuccessRegisterResponse"
                        }
                    },
                    "400": {
                        "description": "[Error message]",
                        "schema": {
                            "$ref": "#/definitions/github_com_HSI-Sandbox-Golang-Team-2025_Team-2_pkg_auth.InvalidRegisterResponse"
                        }
                    }
                }
            }
        },
        "/contents": {
            "get": {
                "description": "Get all learning contents",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Content"
                ],
                "summary": "List contents",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_HSI-Sandbox-Golang-Team-2025_Team-2_pkg_content.Content"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/fiber.Map"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new learning content",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Content"
                ],
                "summary": "Create content",
                "parameters": [
                    {
                        "description": "Content Data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_HSI-Sandbox-Golang-Team-2025_Team-2_pkg_content.Content"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_HSI-Sandbox-Golang-Team-2025_Team-2_pkg_content.Content"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/fiber.Map"
                        }
                    }
                }
            }
        },
        "/contents/{id}": {
            "get": {
                "description": "Get a learning content by its ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Content"
                ],
                "summary": "Get content by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Content ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_HSI-Sandbox-Golang-Team-2025_Team-2_pkg_content.Content"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/fiber.Map"
                        }
                    }
                }
            },
            "put": {
                "description": "Update a learning content by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Content"
                ],
                "summary": "Update content",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Content ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Content Data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_HSI-Sandbox-Golang-Team-2025_Team-2_pkg_content.Content"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_HSI-Sandbox-Golang-Team-2025_Team-2_pkg_content.Content"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/fiber.Map"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a learning content by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Content"
                ],
                "summary": "Delete content",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Content ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "$ref": "#/definitions/fiber.Map"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/fiber.Map"
                        }
                    }
                }
            }
        },
        "/materials": {
            "get": {
                "description": "Get all materials",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Material"
                ],
                "summary": "List materials",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_HSI-Sandbox-Golang-Team-2025_Team-2_pkg_content.Content"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/fiber.Map"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new material",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Material"
                ],
                "summary": "Create material",
                "parameters": [
                    {
                        "description": "Content Data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_HSI-Sandbox-Golang-Team-2025_Team-2_pkg_content.Content"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_HSI-Sandbox-Golang-Team-2025_Team-2_pkg_content.Content"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/fiber.Map"
                        }
                    }
                }
            }
        },
        "/materials/{id}": {
            "get": {
                "description": "Get a material by its ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Material"
                ],
                "summary": "Get material by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Material ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_HSI-Sandbox-Golang-Team-2025_Team-2_pkg_content.Content"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/fiber.Map"
                        }
                    }
                }
            },
            "put": {
                "description": "Update a material by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Material"
                ],
                "summary": "Update material",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Material ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Material Data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_HSI-Sandbox-Golang-Team-2025_Team-2_pkg_content.Content"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_HSI-Sandbox-Golang-Team-2025_Team-2_pkg_content.Content"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/fiber.Map"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a material by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Material"
                ],
                "summary": "Delete material",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Material ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "$ref": "#/definitions/fiber.Map"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/fiber.Map"
                        }
                    }
                }
            }
        },
        "/practices": {
            "post": {
                "description": "Create a new practice",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Practice"
                ],
                "summary": "Create practice",
                "parameters": [
                    {
                        "description": "Practice Data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_HSI-Sandbox-Golang-Team-2025_Team-2_pkg_content.Content"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_HSI-Sandbox-Golang-Team-2025_Team-2_pkg_content.Content"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/fiber.Map"
                        }
                    }
                }
            }
        },
        "/projects": {
            "post": {
                "description": "Create a new project",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Project"
                ],
                "summary": "Create project",
                "parameters": [
                    {
                        "description": "Project Data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_HSI-Sandbox-Golang-Team-2025_Team-2_pkg_content.Content"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_HSI-Sandbox-Golang-Team-2025_Team-2_pkg_content.Content"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/fiber.Map"
                        }
                    }
                }
            }
        },
        "/tracks": {
            "get": {
                "description": "Get all tracks",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Track"
                ],
                "summary": "List tracks",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_HSI-Sandbox-Golang-Team-2025_Team-2_pkg_track.Track"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/fiber.Map"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new track",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Track"
                ],
                "summary": "Create track",
                "parameters": [
                    {
                        "description": "Track Data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_HSI-Sandbox-Golang-Team-2025_Team-2_pkg_track.Track"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_HSI-Sandbox-Golang-Team-2025_Team-2_pkg_track.Track"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/fiber.Map"
                        }
                    }
                }
            }
        },
        "/tracks/{id}": {
            "get": {
                "description": "Get a track by its ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Track"
                ],
                "summary": "Get track by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Track ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_HSI-Sandbox-Golang-Team-2025_Team-2_pkg_track.Track"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/fiber.Map"
                        }
                    }
                }
            },
            "put": {
                "description": "Update a track by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Track"
                ],
                "summary": "Update track",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Track ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Track Data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_HSI-Sandbox-Golang-Team-2025_Team-2_pkg_track.Track"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_HSI-Sandbox-Golang-Team-2025_Team-2_pkg_track.Track"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/fiber.Map"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a track by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Track"
                ],
                "summary": "Delete track",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Track ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "$ref": "#/definitions/fiber.Map"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/fiber.Map"
                        }
                    }
                }
            }
        },
        "/user-materials": {
            "get": {
                "description": "Get all user materials",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "UserMaterial"
                ],
                "summary": "List user materials",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_HSI-Sandbox-Golang-Team-2025_Team-2_pkg_user_material.UserMaterial"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/fiber.Map"
                        }
                    }
                }
            },
            "post": {
                "description": "Register a material for a user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "UserMaterial"
                ],
                "summary": "Create user material",
                "parameters": [
                    {
                        "description": "UserMaterial Data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_HSI-Sandbox-Golang-Team-2025_Team-2_pkg_user_material.UserMaterial"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_HSI-Sandbox-Golang-Team-2025_Team-2_pkg_user_material.UserMaterial"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/fiber.Map"
                        }
                    }
                }
            }
        },
        "/user-materials/{id}": {
            "get": {
                "description": "Get a user material by its ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "UserMaterial"
                ],
                "summary": "Get user material by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "UserMaterial ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_HSI-Sandbox-Golang-Team-2025_Team-2_pkg_user_material.UserMaterial"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/fiber.Map"
                        }
                    }
                }
            },
            "put": {
                "description": "Update a user material by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "UserMaterial"
                ],
                "summary": "Update user material",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "UserMaterial ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "UserMaterial Data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_HSI-Sandbox-Golang-Team-2025_Team-2_pkg_user_material.UserMaterial"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_HSI-Sandbox-Golang-Team-2025_Team-2_pkg_user_material.UserMaterial"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/fiber.Map"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a user material by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "UserMaterial"
                ],
                "summary": "Delete user material",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "UserMaterial ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "$ref": "#/definitions/fiber.Map"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/fiber.Map"
                        }
                    }
                }
            }
        },
        "/user-practices": {
            "get": {
                "description": "Get all user practices",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "UserPractice"
                ],
                "summary": "List user practices",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_HSI-Sandbox-Golang-Team-2025_Team-2_pkg_user_practice.UserPractice"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/fiber.Map"
                        }
                    }
                }
            }
        },
        "/user-practices/{id}/review": {
            "patch": {
                "description": "Review a user practice by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "UserPractice"
                ],
                "summary": "Review user practice",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "UserPractice ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Review Data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_HSI-Sandbox-Golang-Team-2025_Team-2_pkg_user_practice.UserPractice"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_HSI-Sandbox-Golang-Team-2025_Team-2_pkg_user_practice.UserPractice"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/fiber.Map"
                        }
                    }
                }
            }
        },
        "/user-practices/{id}/start": {
            "patch": {
                "description": "Start a user practice by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "UserPractice"
                ],
                "summary": "Start user practice",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "UserPractice ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_HSI-Sandbox-Golang-Team-2025_Team-2_pkg_user_practice.UserPractice"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/fiber.Map"
                        }
                    }
                }
            }
        },
        "/user-practices/{id}/submit": {
            "patch": {
                "description": "Submit answers for a user practice",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "UserPractice"
                ],
                "summary": "Submit user practice",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "UserPractice ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "UserPractice Data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_HSI-Sandbox-Golang-Team-2025_Team-2_pkg_user_practice.UserPractice"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_HSI-Sandbox-Golang-Team-2025_Team-2_pkg_user_practice.UserPractice"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/fiber.Map"
                        }
                    }
                }
            }
        },
        "/user-projects": {
            "get": {
                "description": "Get all user projects",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "UserProject"
                ],
                "summary": "List user projects",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_HSI-Sandbox-Golang-Team-2025_Team-2_pkg_user_project.UserProject"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/fiber.Map"
                        }
                    }
                }
            },
            "post": {
                "description": "Start a user project",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "UserProject"
                ],
                "summary": "Start user project",
                "parameters": [
                    {
                        "description": "UserProject Data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_HSI-Sandbox-Golang-Team-2025_Team-2_pkg_user_project.UserProject"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_HSI-Sandbox-Golang-Team-2025_Team-2_pkg_user_project.UserProject"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/fiber.Map"
                        }
                    }
                }
            }
        },
        "/user-projects/{id}/review": {
            "patch": {
                "description": "Review a user project by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "UserProject"
                ],
                "summary": "Review user project",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "UserProject ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Review Data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_HSI-Sandbox-Golang-Team-2025_Team-2_pkg_user_project.UserProject"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_HSI-Sandbox-Golang-Team-2025_Team-2_pkg_user_project.UserProject"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/fiber.Map"
                        }
                    }
                }
            }
        },
        "/user-projects/{id}/submit": {
            "patch": {
                "description": "Submit a user project by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "UserProject"
                ],
                "summary": "Submit user project",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "UserProject ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "UserProject Data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_HSI-Sandbox-Golang-Team-2025_Team-2_pkg_user_project.UserProject"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_HSI-Sandbox-Golang-Team-2025_Team-2_pkg_user_project.UserProject"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/fiber.Map"
                        }
                    }
                }
            }
        },
        "/user-tracks": {
            "get": {
                "description": "Get all user tracks",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "UserTrack"
                ],
                "summary": "List user tracks",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_HSI-Sandbox-Golang-Team-2025_Team-2_pkg_user_track.UserTrack"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/fiber.Map"
                        }
                    }
                }
            },
            "post": {
                "description": "Register a track for a user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "UserTrack"
                ],
                "summary": "Create user track",
                "parameters": [
                    {
                        "description": "UserTrack Data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_HSI-Sandbox-Golang-Team-2025_Team-2_pkg_user_track.UserTrack"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_HSI-Sandbox-Golang-Team-2025_Team-2_pkg_user_track.UserTrack"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/fiber.Map"
                        }
                    }
                }
            }
        },
        "/user-tracks/{id}": {
            "get": {
                "description": "Get a user track by its ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "UserTrack"
                ],
                "summary": "Get user track by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "UserTrack ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_HSI-Sandbox-Golang-Team-2025_Team-2_pkg_user_track.UserTrack"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/fiber.Map"
                        }
                    }
                }
            },
            "put": {
                "description": "Update a user track by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "UserTrack"
                ],
                "summary": "Update user track",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "UserTrack ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "UserTrack Data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_HSI-Sandbox-Golang-Team-2025_Team-2_pkg_user_track.UserTrack"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_HSI-Sandbox-Golang-Team-2025_Team-2_pkg_user_track.UserTrack"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/fiber.Map"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a user track by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "UserTrack"
                ],
                "summary": "Delete user track",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "UserTrack ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "$ref": "#/definitions/fiber.Map"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/fiber.Map"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "fiber.Map": {
            "type": "object",
            "additionalProperties": true
        },
        "github_com_HSI-Sandbox-Golang-Team-2025_Team-2_pkg_auth.InvalidLoginResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "email or password is incorrect"
                },
                "message": {
                    "type": "string",
                    "example": "Invalid credentials!"
                }
            }
        },
        "github_com_HSI-Sandbox-Golang-Team-2025_Team-2_pkg_auth.InvalidRegisterResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "email or password is incorrect"
                },
                "message": {
                    "type": "string",
                    "example": "Invalid credentials!"
                }
            }
        },
        "github_com_HSI-Sandbox-Golang-Team-2025_Team-2_pkg_auth.LoginBody": {
            "type": "object",
            "properties": {
                "nip": {
                    "type": "string",
                    "example": "ARN-2402001"
                },
                "password": {
                    "type": "string",
                    "example": "123"
                }
            }
        },
        "github_com_HSI-Sandbox-Golang-Team-2025_Team-2_pkg_auth.RegisterBody": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "example": "Luthfi"
                },
                "nip": {
                    "type": "string",
                    "example": "ARN-2402009"
                },
                "password": {
                    "type": "string",
                    "example": "123"
                }
            }
        },
        "github_com_HSI-Sandbox-Golang-Team-2025_Team-2_pkg_auth.SuccessLoginResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/github_com_HSI-Sandbox-Golang-Team-2025_Team-2_pkg_auth.TokenData"
                },
                "message": {
                    "type": "string",
                    "example": "Login success!"
                }
            }
        },
        "github_com_HSI-Sandbox-Golang-Team-2025_Team-2_pkg_auth.SuccessRegisterResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/github_com_HSI-Sandbox-Golang-Team-2025_Team-2_pkg_auth.TokenData"
                },
                "message": {
                    "type": "string",
                    "example": "Login success!"
                }
            }
        },
        "github_com_HSI-Sandbox-Golang-Team-2025_Team-2_pkg_auth.TokenData": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string",
                    "example": "eyJhbGciOiJI..."
                }
            }
        },
        "github_com_HSI-Sandbox-Golang-Team-2025_Team-2_pkg_content.Content": {
            "type": "object",
            "properties": {
                "body": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "isCompleted": {
                    "type": "boolean"
                },
                "order": {
                    "type": "integer"
                },
                "questions": {
                    "type": "string",
                    "example": "null"
                },
                "title": {
                    "type": "string"
                },
                "trackId": {
                    "type": "integer"
                },
                "type": {
                    "$ref": "#/definitions/github_com_HSI-Sandbox-Golang-Team-2025_Team-2_pkg_content.ContentType"
                },
                "updatedAt": {
                    "type": "string"
                },
                "userPractices": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_HSI-Sandbox-Golang-Team-2025_Team-2_pkg_user_practice.UserPractice"
                    }
                }
            }
        },
        "github_com_HSI-Sandbox-Golang-Team-2025_Team-2_pkg_content.ContentType": {
            "type": "string",
            "enum": [
                "material",
                "practice",
                "project"
            ],
            "x-enum-varnames": [
                "ContentTypeMaterial",
                "ContentTypePractice",
                "ContentTypeProject"
            ]
        },
        "github_com_HSI-Sandbox-Golang-Team-2025_Team-2_pkg_role.Role": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "github_com_HSI-Sandbox-Golang-Team-2025_Team-2_pkg_track.Track": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "github_com_HSI-Sandbox-Golang-Team-2025_Team-2_pkg_user.User": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "nip": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "role": {
                    "$ref": "#/definitions/github_com_HSI-Sandbox-Golang-Team-2025_Team-2_pkg_role.Role"
                },
                "roleId": {
                    "type": "integer"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "github_com_HSI-Sandbox-Golang-Team-2025_Team-2_pkg_user_material.UserMaterial": {
            "type": "object",
            "properties": {
                "content_id": {
                    "type": "integer"
                },
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "id": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "github_com_HSI-Sandbox-Golang-Team-2025_Team-2_pkg_user_practice.UserPractice": {
            "type": "object",
            "properties": {
                "comment": {
                    "type": "string"
                },
                "contentId": {
                    "type": "integer"
                },
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "score": {
                    "type": "number"
                },
                "status": {
                    "$ref": "#/definitions/github_com_HSI-Sandbox-Golang-Team-2025_Team-2_pkg_user_practice.UserPracticeStatus"
                },
                "updatedAt": {
                    "type": "string"
                },
                "user": {
                    "type": "string"
                },
                "userId": {
                    "type": "integer"
                },
                "userPracticeRecords": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_HSI-Sandbox-Golang-Team-2025_Team-2_pkg_user_practice_record.UserPracticeRecord"
                    }
                }
            }
        },
        "github_com_HSI-Sandbox-Golang-Team-2025_Team-2_pkg_user_practice.UserPracticeStatus": {
            "type": "string",
            "enum": [
                "opened",
                "in progress",
                "submitted",
                "reviewed"
            ],
            "x-enum-varnames": [
                "Opened",
                "InProgress",
                "Submitted",
                "Reviewed"
            ]
        },
        "github_com_HSI-Sandbox-Golang-Team-2025_Team-2_pkg_user_practice_record.UserPracticeRecord": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "isCorrect": {
                    "type": "boolean"
                },
                "question": {
                    "type": "string"
                },
                "questionAnswerChoice": {
                    "type": "string"
                },
                "questionAnswerChoiceId": {
                    "type": "integer"
                },
                "questionAnswerText": {
                    "type": "string"
                },
                "questionId": {
                    "type": "integer"
                },
                "updatedAt": {
                    "type": "string"
                },
                "userPracticeId": {
                    "type": "integer"
                }
            }
        },
        "github_com_HSI-Sandbox-Golang-Team-2025_Team-2_pkg_user_project.UserProject": {
            "type": "object",
            "properties": {
                "comment": {
                    "type": "string"
                },
                "content": {
                    "$ref": "#/definitions/github_com_HSI-Sandbox-Golang-Team-2025_Team-2_pkg_content.Content"
                },
                "contentId": {
                    "type": "integer"
                },
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "medias": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_HSI-Sandbox-Golang-Team-2025_Team-2_pkg_user_project_media.UserProjectMedia"
                    }
                },
                "score": {
                    "type": "number"
                },
                "status": {
                    "$ref": "#/definitions/github_com_HSI-Sandbox-Golang-Team-2025_Team-2_pkg_user_project.UserProjectStatus"
                },
                "updatedAt": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/github_com_HSI-Sandbox-Golang-Team-2025_Team-2_pkg_user.User"
                },
                "userId": {
                    "type": "integer"
                }
            }
        },
        "github_com_HSI-Sandbox-Golang-Team-2025_Team-2_pkg_user_project.UserProjectStatus": {
            "type": "string",
            "enum": [
                "in progress",
                "submitted",
                "rejected",
                "approved"
            ],
            "x-enum-varnames": [
                "InProgress",
                "Submitted",
                "Rejected",
                "Approved"
            ]
        },
        "github_com_HSI-Sandbox-Golang-Team-2025_Team-2_pkg_user_project_media.UserProjectMedia": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                },
                "userProjectId": {
                    "type": "integer"
                }
            }
        },
        "github_com_HSI-Sandbox-Golang-Team-2025_Team-2_pkg_user_track.UserTrack": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "track": {
                    "$ref": "#/definitions/github_com_HSI-Sandbox-Golang-Team-2025_Team-2_pkg_track.Track"
                },
                "trackId": {
                    "type": "integer"
                },
                "updatedAt": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/github_com_HSI-Sandbox-Golang-Team-2025_Team-2_pkg_user.User"
                },
                "userId": {
                    "type": "integer"
                }
            }
        },
        "gorm.DeletedAt": {
            "type": "object",
            "properties": {
                "time": {
                    "type": "string"
                },
                "valid": {
                    "description": "Valid is true if Time is not NULL",
                    "type": "boolean"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Type \"Bearer\" followed by a space and JWT token.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:3000",
	BasePath:         "/api",
	Schemes:          []string{"http"},
	Title:            "Learning Platform",
	Description:      "Learning Platform API Documentations",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
