// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "description": "Authenticate user with static credentials and return JWT token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "User login",
                "parameters": [
                    {
                        "description": "Login credentials",
                        "name": "credentials",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.LoginBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Login success!",
                        "schema": {
                            "$ref": "#/definitions/handler.SuccessLoginResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid credentials!",
                        "schema": {
                            "$ref": "#/definitions/handler.InvalidLoginResponse"
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "description": "Register a user and return a JWT token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "User register",
                "parameters": [
                    {
                        "description": "New user data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.RegisterBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Registration success!",
                        "schema": {
                            "$ref": "#/definitions/handler.SuccessRegisterResponse"
                        }
                    },
                    "400": {
                        "description": "Registration failed!",
                        "schema": {
                            "$ref": "#/definitions/handler.InvalidRegisterResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handler.InvalidLoginResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Invalid Credentials!"
                }
            }
        },
        "handler.InvalidRegisterResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Registration failed!"
                }
            }
        },
        "handler.LoginBody": {
            "type": "object",
            "properties": {
                "nip": {
                    "type": "string",
                    "example": "ARN-2402001"
                },
                "password": {
                    "type": "string",
                    "example": "123"
                }
            }
        },
        "handler.RegisterBody": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "example": "Teguh"
                },
                "nip": {
                    "type": "string",
                    "example": "ARN-2402001"
                },
                "password": {
                    "type": "string",
                    "example": "123"
                }
            }
        },
        "handler.SuccessLoginData": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUz.."
                }
            }
        },
        "handler.SuccessLoginResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/handler.SuccessLoginData"
                },
                "message": {
                    "type": "string",
                    "example": "Login success!"
                }
            }
        },
        "handler.SuccessRegisterData": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUz.."
                }
            }
        },
        "handler.SuccessRegisterResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/handler.SuccessRegisterData"
                },
                "message": {
                    "type": "string",
                    "example": "Registration success!"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Type \"Bearer\" followed by a space and JWT token.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:3000",
	BasePath:         "/api",
	Schemes:          []string{"http"},
	Title:            "Learning Platform",
	Description:      "Learning Platform API Documentations",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
