// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "description": "Authenticate user with static credentials and return JWT token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "User login",
                "parameters": [
                    {
                        "description": "Login credentials",
                        "name": "credentials",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/pkg_auth_handler.LoginBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Login success!",
                        "schema": {
                            "$ref": "#/definitions/pkg_auth_handler.SuccessLoginResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid credentials!",
                        "schema": {
                            "$ref": "#/definitions/pkg_auth_handler.InvalidLoginResponse"
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "description": "Register a user and return a JWT token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "User register",
                "parameters": [
                    {
                        "description": "New user data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/pkg_auth_handler.RegisterBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Registration success!",
                        "schema": {
                            "$ref": "#/definitions/pkg_auth_handler.SuccessRegisterResponse"
                        }
                    },
                    "400": {
                        "description": "[Error message]",
                        "schema": {
                            "$ref": "#/definitions/pkg_auth_handler.InvalidRegisterResponse"
                        }
                    }
                }
            }
        },
        "/contents": {
            "get": {
                "description": "Get learning contents (materials, practices and projects)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Contents"
                ],
                "summary": "Get learning contents",
                "parameters": [
                    {
                        "type": "string",
                        "example": "1",
                        "description": "track.id",
                        "name": "trackId",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Get contents success!",
                        "schema": {
                            "$ref": "#/definitions/pkg_content_handler.GetContentsSuccessResponse"
                        }
                    }
                }
            }
        },
        "/contents/{id}": {
            "get": {
                "description": "Get learning content (materials, practices and projects)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Contents"
                ],
                "summary": "Get learning content",
                "parameters": [
                    {
                        "type": "integer",
                        "example": 1,
                        "description": "content.id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Get content success!",
                        "schema": {
                            "$ref": "#/definitions/pkg_content_handler.GetContentSuccessResponse"
                        }
                    }
                }
            }
        },
        "/contents/{id}/questions": {
            "get": {
                "description": "Get practice questions",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Questions"
                ],
                "summary": "Get practice questions",
                "responses": {}
            }
        },
        "/practices": {
            "post": {
                "description": "Create a new practice content",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Practice"
                ],
                "summary": "Create practice content",
                "parameters": [
                    {
                        "description": "Create practice content data",
                        "name": "credentials",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/pkg_practice_handler.CreatePracticeBody"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Get practice content success!",
                        "schema": {
                            "$ref": "#/definitions/pkg_practice_handler.CreatePracticeSuccessResponse"
                        }
                    },
                    "500": {
                        "description": "Error",
                        "schema": {
                            "$ref": "#/definitions/pkg_practice_handler.CreatePracticeErrorResponse"
                        }
                    }
                }
            }
        },
        "/projects": {
            "post": {
                "description": "Create a new project content",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Project"
                ],
                "summary": "Create project content",
                "parameters": [
                    {
                        "description": "Create project content data",
                        "name": "credentials",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/pkg_project_handler.CreateProjectBody"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Get project content success!",
                        "schema": {
                            "$ref": "#/definitions/pkg_project_handler.CreateProjectSuccessResponse"
                        }
                    },
                    "500": {
                        "description": "Error",
                        "schema": {
                            "$ref": "#/definitions/pkg_project_handler.CreateProjectErrorResponse"
                        }
                    }
                }
            }
        },
        "/user-practices": {
            "get": {
                "description": "Authenticate user with static credentials and return JWT token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Backlog"
                ],
                "summary": "User login",
                "responses": {}
            },
            "post": {
                "description": "Authenticate user with static credentials and return JWT token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Backlog"
                ],
                "summary": "User login",
                "responses": {}
            }
        },
        "/user-practices/:id/review": {
            "patch": {
                "description": "Authenticate user with static credentials and return JWT token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Backlog"
                ],
                "summary": "User login",
                "responses": {}
            }
        },
        "/user-practices/:id/submit": {
            "patch": {
                "description": "Authenticate user with static credentials and return JWT token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Backlog"
                ],
                "summary": "User login",
                "responses": {}
            }
        },
        "/user-projects": {
            "get": {
                "description": "Authenticate user with static credentials and return JWT token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Backlog"
                ],
                "summary": "Get user projects",
                "responses": {}
            },
            "post": {
                "description": "Authenticate user with static credentials and return JWT token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Backlog"
                ],
                "summary": "Start user project",
                "responses": {}
            }
        },
        "/user-projects/:id/review": {
            "patch": {
                "description": "Authenticate user with static credentials and return JWT token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Backlog"
                ],
                "summary": "Review user projects",
                "responses": {}
            }
        },
        "/user-projects/:id/submit": {
            "patch": {
                "description": "Authenticate user with static credentials and return JWT token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Backlog"
                ],
                "summary": "Submit user project",
                "responses": {}
            }
        }
    },
    "definitions": {
        "github_com_HSI-Sandbox-Golang-Team-2025_Team-2_pkg_content.Content": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "x-order": "00"
                },
                "createdAt": {
                    "type": "string",
                    "x-order": "01",
                    "example": "2025-10-18T14:42:51.9782263+07:00"
                },
                "updatedAt": {
                    "type": "string",
                    "x-order": "02",
                    "example": "2025-10-18T14:42:51.9782263+07:00"
                },
                "deletedAt": {
                    "type": "string",
                    "x-order": "03",
                    "example": "null"
                },
                "trackId": {
                    "type": "integer",
                    "x-order": "04",
                    "example": 1
                },
                "title": {
                    "type": "string",
                    "x-order": "05",
                    "example": "Latihan 2"
                },
                "body": {
                    "type": "string",
                    "x-order": "06",
                    "example": "Latihan ini anda akan menguji kemampuan React anda"
                },
                "type": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_HSI-Sandbox-Golang-Team-2025_Team-2_pkg_content.ContentType"
                        }
                    ],
                    "x-order": "07",
                    "example": "practice"
                },
                "order": {
                    "type": "integer",
                    "x-order": "08",
                    "example": 1
                },
                "questions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_HSI-Sandbox-Golang-Team-2025_Team-2_pkg_question.Question"
                    },
                    "x-order": "09"
                },
                "isCompleted": {
                    "type": "boolean",
                    "x-order": "10",
                    "example": false
                },
                "userPractices": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_HSI-Sandbox-Golang-Team-2025_Team-2_pkg_user_practice.UserPractice"
                    },
                    "x-order": "11"
                }
            }
        },
        "github_com_HSI-Sandbox-Golang-Team-2025_Team-2_pkg_content.ContentType": {
            "type": "string",
            "enum": [
                "material",
                "practice",
                "project"
            ],
            "x-enum-varnames": [
                "ContentTypeMaterial",
                "ContentTypePractice",
                "ContentTypeProject"
            ]
        },
        "github_com_HSI-Sandbox-Golang-Team-2025_Team-2_pkg_question.Question": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "x-order": "00"
                },
                "createdAt": {
                    "type": "string",
                    "x-order": "01",
                    "example": "2025-10-18T14:42:51.9782263+07:00"
                },
                "updatedAt": {
                    "type": "string",
                    "x-order": "02",
                    "example": "2025-10-18T14:42:51.9782263+07:00"
                },
                "deletedAt": {
                    "type": "string",
                    "x-order": "03",
                    "example": "null"
                },
                "contentId": {
                    "type": "integer",
                    "x-order": "04",
                    "example": 1
                },
                "answerChoices": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_HSI-Sandbox-Golang-Team-2025_Team-2_pkg_question_answer_choice.QuestionAnswerChoice"
                    },
                    "x-order": "05"
                },
                "question": {
                    "type": "string",
                    "x-order": "05",
                    "example": "Apakah 1 + 1 = 2"
                }
            }
        },
        "github_com_HSI-Sandbox-Golang-Team-2025_Team-2_pkg_question_answer_choice.QuestionAnswerChoice": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "x-order": "00"
                },
                "createdAt": {
                    "type": "string",
                    "x-order": "01",
                    "example": "2025-10-18T14:42:51.9782263+07:00"
                },
                "updatedAt": {
                    "type": "string",
                    "x-order": "02",
                    "example": "2025-10-18T14:42:51.9782263+07:00"
                },
                "deletedAt": {
                    "type": "string",
                    "x-order": "03",
                    "example": "null"
                },
                "questionId": {
                    "type": "integer",
                    "x-order": "04",
                    "example": 1
                },
                "answer": {
                    "type": "string",
                    "x-order": "05",
                    "example": "Benar"
                }
            }
        },
        "github_com_HSI-Sandbox-Golang-Team-2025_Team-2_pkg_user_practice.UserPractice": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "x-order": "00"
                },
                "createdAt": {
                    "type": "string",
                    "x-order": "01",
                    "example": "2025-10-18T14:42:51.9782263+07:00"
                },
                "updatedAt": {
                    "type": "string",
                    "x-order": "02",
                    "example": "2025-10-18T14:42:51.9782263+07:00"
                },
                "deletedAt": {
                    "type": "string",
                    "x-order": "03",
                    "example": "null"
                },
                "userId": {
                    "type": "integer",
                    "x-order": "04",
                    "example": 1
                },
                "user": {
                    "type": "string",
                    "x-order": "05"
                },
                "contentId": {
                    "type": "integer",
                    "x-order": "06",
                    "example": 1
                },
                "status": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_HSI-Sandbox-Golang-Team-2025_Team-2_pkg_user_practice.UserPracticeStatus"
                        }
                    ],
                    "x-order": "07",
                    "example": "opened"
                },
                "score": {
                    "type": "number",
                    "x-order": "08",
                    "example": 100
                },
                "comment": {
                    "type": "string",
                    "x-order": "09",
                    "example": "Good job!"
                },
                "userPracticeRecords": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_HSI-Sandbox-Golang-Team-2025_Team-2_pkg_user_practice_record.UserPracticeRecord"
                    },
                    "x-order": "10"
                }
            }
        },
        "github_com_HSI-Sandbox-Golang-Team-2025_Team-2_pkg_user_practice.UserPracticeStatus": {
            "type": "string",
            "enum": [
                "in progress",
                "submitted",
                "reviewed"
            ],
            "x-enum-varnames": [
                "InProgress",
                "Submitted",
                "Reviewed"
            ]
        },
        "github_com_HSI-Sandbox-Golang-Team-2025_Team-2_pkg_user_practice_record.UserPracticeRecord": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "x-order": "00"
                },
                "createdAt": {
                    "type": "string",
                    "x-order": "01",
                    "example": "2025-10-18T14:42:51.9782263+07:00"
                },
                "updatedAt": {
                    "type": "string",
                    "x-order": "02",
                    "example": "2025-10-18T14:42:51.9782263+07:00"
                },
                "deletedAt": {
                    "type": "string",
                    "x-order": "03",
                    "example": "null"
                },
                "isCorrect": {
                    "type": "boolean"
                },
                "question": {
                    "type": "string"
                },
                "questionAnswerChoice": {
                    "type": "string"
                },
                "questionAnswerChoiceId": {
                    "type": "integer"
                },
                "questionAnswerText": {
                    "type": "string"
                },
                "questionId": {
                    "type": "integer"
                },
                "userPracticeId": {
                    "type": "integer"
                }
            }
        },
        "pkg_auth_handler.InvalidLoginResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Invalid Credentials!"
                }
            }
        },
        "pkg_auth_handler.InvalidRegisterResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Registration failed!"
                }
            }
        },
        "pkg_auth_handler.LoginBody": {
            "type": "object",
            "properties": {
                "nip": {
                    "type": "string",
                    "example": "ARN-2402001"
                },
                "password": {
                    "type": "string",
                    "example": "123"
                }
            }
        },
        "pkg_auth_handler.RegisterBody": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "example": "Teguh"
                },
                "nip": {
                    "type": "string",
                    "example": "ARN-2402001"
                },
                "password": {
                    "type": "string",
                    "example": "123"
                }
            }
        },
        "pkg_auth_handler.SuccessLoginData": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUz.."
                }
            }
        },
        "pkg_auth_handler.SuccessLoginResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/pkg_auth_handler.SuccessLoginData"
                },
                "message": {
                    "type": "string",
                    "example": "Login success!"
                }
            }
        },
        "pkg_auth_handler.SuccessRegisterData": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUz.."
                }
            }
        },
        "pkg_auth_handler.SuccessRegisterResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/pkg_auth_handler.SuccessRegisterData"
                },
                "message": {
                    "type": "string",
                    "example": "Registration success!"
                }
            }
        },
        "pkg_content_handler.GetContentSuccessResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/github_com_HSI-Sandbox-Golang-Team-2025_Team-2_pkg_content.Content"
                },
                "message": {
                    "type": "string",
                    "example": "Get content success!"
                }
            }
        },
        "pkg_content_handler.GetContentsSuccessResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_HSI-Sandbox-Golang-Team-2025_Team-2_pkg_content.Content"
                    }
                },
                "message": {
                    "type": "string",
                    "example": "Get content success!"
                }
            }
        },
        "pkg_practice_handler.AnswerChoice": {
            "type": "object",
            "properties": {
                "answer": {
                    "type": "string",
                    "example": "Benar"
                }
            }
        },
        "pkg_practice_handler.Content": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "x-order": "00"
                },
                "createdAt": {
                    "type": "string",
                    "x-order": "01",
                    "example": "2025-10-18T14:42:51.9782263+07:00"
                },
                "updatedAt": {
                    "type": "string",
                    "x-order": "02",
                    "example": "2025-10-18T14:42:51.9782263+07:00"
                },
                "deletedAt": {
                    "type": "string",
                    "x-order": "03",
                    "example": "null"
                },
                "trackId": {
                    "type": "integer",
                    "x-order": "04",
                    "example": 1
                },
                "title": {
                    "type": "string",
                    "x-order": "05",
                    "example": "Latihan 2"
                },
                "body": {
                    "type": "string",
                    "x-order": "06",
                    "example": "Latihan ini anda akan menguji kemampuan React anda"
                },
                "type": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_HSI-Sandbox-Golang-Team-2025_Team-2_pkg_content.ContentType"
                        }
                    ],
                    "x-order": "07",
                    "example": "practice"
                },
                "order": {
                    "type": "integer",
                    "x-order": "08",
                    "example": 1
                },
                "questions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_HSI-Sandbox-Golang-Team-2025_Team-2_pkg_question.Question"
                    },
                    "x-order": "09"
                },
                "isCompleted": {
                    "type": "boolean",
                    "x-order": "10",
                    "example": false
                },
                "userPractices": {
                    "type": "string",
                    "x-order": "11",
                    "example": "null"
                }
            }
        },
        "pkg_practice_handler.CreatePracticeBody": {
            "type": "object",
            "properties": {
                "body": {
                    "type": "string",
                    "example": "Latihan ini anda akan menguji kemampuan React anda"
                },
                "questions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/pkg_practice_handler.Question"
                    }
                },
                "title": {
                    "type": "string",
                    "example": "Latihan 2"
                },
                "trackId": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "pkg_practice_handler.CreatePracticeErrorResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "[Error message]"
                }
            }
        },
        "pkg_practice_handler.CreatePracticeSuccessResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/pkg_practice_handler.Content"
                },
                "message": {
                    "type": "string",
                    "example": "Create practice content success!"
                }
            }
        },
        "pkg_practice_handler.Question": {
            "type": "object",
            "properties": {
                "answerChoices": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/pkg_practice_handler.AnswerChoice"
                    }
                },
                "question": {
                    "type": "string",
                    "example": "Apakah 1 + 1 = 2"
                }
            }
        },
        "pkg_project_handler.Content": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "x-order": "00"
                },
                "createdAt": {
                    "type": "string",
                    "x-order": "01",
                    "example": "2025-10-18T14:42:51.9782263+07:00"
                },
                "updatedAt": {
                    "type": "string",
                    "x-order": "02",
                    "example": "2025-10-18T14:42:51.9782263+07:00"
                },
                "deletedAt": {
                    "type": "string",
                    "x-order": "03",
                    "example": "null"
                },
                "trackId": {
                    "type": "integer",
                    "x-order": "04",
                    "example": 1
                },
                "title": {
                    "type": "string",
                    "x-order": "05",
                    "example": "Latihan 2"
                },
                "body": {
                    "type": "string",
                    "x-order": "06",
                    "example": "Latihan ini anda akan menguji kemampuan React anda"
                },
                "type": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_HSI-Sandbox-Golang-Team-2025_Team-2_pkg_content.ContentType"
                        }
                    ],
                    "x-order": "07",
                    "example": "practice"
                },
                "order": {
                    "type": "integer",
                    "x-order": "08",
                    "example": 1
                },
                "questions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_HSI-Sandbox-Golang-Team-2025_Team-2_pkg_question.Question"
                    },
                    "x-order": "09"
                },
                "isCompleted": {
                    "type": "boolean",
                    "x-order": "10",
                    "example": false
                },
                "userProjects": {
                    "type": "string",
                    "x-order": "11",
                    "example": "null"
                },
                "userPractices": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_HSI-Sandbox-Golang-Team-2025_Team-2_pkg_user_practice.UserPractice"
                    },
                    "x-order": "11"
                }
            }
        },
        "pkg_project_handler.CreateProjectBody": {
            "type": "object",
            "properties": {
                "body": {
                    "type": "string",
                    "example": "Anda akan diminta untuk membuat final project"
                },
                "title": {
                    "type": "string",
                    "example": "Final Project"
                },
                "trackId": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "pkg_project_handler.CreateProjectErrorResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "[Error message]"
                }
            }
        },
        "pkg_project_handler.CreateProjectSuccessResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/pkg_project_handler.Content"
                },
                "message": {
                    "type": "string",
                    "example": "Create project content success!"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Type \"Bearer\" followed by a space and JWT token.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:3000",
	BasePath:         "/api",
	Schemes:          []string{"http"},
	Title:            "Learning Platform",
	Description:      "Learning Platform API Documentations",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
