basePath: /api
definitions:
  github_com_HSI-Sandbox-Golang-Team-2025_Team-2_pkg_content.Content:
    properties:
      body:
        example: Latihan ini anda akan menguji kemampuan React anda
        type: string
        x-order: "06"
      createdAt:
        example: "2025-10-18T14:42:51.9782263+07:00"
        type: string
        x-order: "01"
      deletedAt:
        example: "null"
        type: string
        x-order: "03"
      id:
        type: integer
        x-order: "00"
      isCompleted:
        example: false
        type: boolean
        x-order: "10"
      order:
        example: 1
        type: integer
        x-order: "08"
      questions:
        items:
          $ref: '#/definitions/github_com_HSI-Sandbox-Golang-Team-2025_Team-2_pkg_question.Question'
        type: array
        x-order: "09"
      title:
        example: Latihan 2
        type: string
        x-order: "05"
      trackId:
        example: 1
        type: integer
        x-order: "04"
      type:
        allOf:
        - $ref: '#/definitions/github_com_HSI-Sandbox-Golang-Team-2025_Team-2_pkg_content.ContentType'
        example: practice
        x-order: "07"
      updatedAt:
        example: "2025-10-18T14:42:51.9782263+07:00"
        type: string
        x-order: "02"
      userPractices:
        items:
          $ref: '#/definitions/github_com_HSI-Sandbox-Golang-Team-2025_Team-2_pkg_user_practice.UserPractice'
        type: array
        x-order: "11"
    type: object
  github_com_HSI-Sandbox-Golang-Team-2025_Team-2_pkg_content.ContentType:
    enum:
    - material
    - practice
    - project
    type: string
    x-enum-varnames:
    - ContentTypeMaterial
    - ContentTypePractice
    - ContentTypeProject
  github_com_HSI-Sandbox-Golang-Team-2025_Team-2_pkg_question.Question:
    properties:
      answerChoices:
        items:
          $ref: '#/definitions/github_com_HSI-Sandbox-Golang-Team-2025_Team-2_pkg_question_answer_choice.QuestionAnswerChoice'
        type: array
        x-order: "05"
      contentId:
        example: 1
        type: integer
        x-order: "04"
      createdAt:
        example: "2025-10-18T14:42:51.9782263+07:00"
        type: string
        x-order: "01"
      deletedAt:
        example: "null"
        type: string
        x-order: "03"
      id:
        type: integer
        x-order: "00"
      question:
        example: Apakah 1 + 1 = 2
        type: string
        x-order: "05"
      updatedAt:
        example: "2025-10-18T14:42:51.9782263+07:00"
        type: string
        x-order: "02"
    type: object
  github_com_HSI-Sandbox-Golang-Team-2025_Team-2_pkg_question_answer_choice.QuestionAnswerChoice:
    properties:
      answer:
        example: Benar
        type: string
        x-order: "05"
      createdAt:
        example: "2025-10-18T14:42:51.9782263+07:00"
        type: string
        x-order: "01"
      deletedAt:
        example: "null"
        type: string
        x-order: "03"
      id:
        type: integer
        x-order: "00"
      questionId:
        example: 1
        type: integer
        x-order: "04"
      updatedAt:
        example: "2025-10-18T14:42:51.9782263+07:00"
        type: string
        x-order: "02"
    type: object
  github_com_HSI-Sandbox-Golang-Team-2025_Team-2_pkg_user_practice.UserPractice:
    properties:
      comment:
        example: Good job!
        type: string
        x-order: "09"
      contentId:
        example: 1
        type: integer
        x-order: "06"
      createdAt:
        example: "2025-10-18T14:42:51.9782263+07:00"
        type: string
        x-order: "01"
      deletedAt:
        example: "null"
        type: string
        x-order: "03"
      id:
        type: integer
        x-order: "00"
      score:
        example: 100
        type: number
        x-order: "08"
      status:
        allOf:
        - $ref: '#/definitions/github_com_HSI-Sandbox-Golang-Team-2025_Team-2_pkg_user_practice.UserPracticeStatus'
        example: opened
        x-order: "07"
      updatedAt:
        example: "2025-10-18T14:42:51.9782263+07:00"
        type: string
        x-order: "02"
      user:
        type: string
        x-order: "05"
      userId:
        example: 1
        type: integer
        x-order: "04"
      userPracticeRecords:
        items:
          $ref: '#/definitions/github_com_HSI-Sandbox-Golang-Team-2025_Team-2_pkg_user_practice_record.UserPracticeRecord'
        type: array
        x-order: "10"
    type: object
  github_com_HSI-Sandbox-Golang-Team-2025_Team-2_pkg_user_practice.UserPracticeStatus:
    enum:
    - opened
    - in progress
    - submitted
    - reviewed
    type: string
    x-enum-varnames:
    - Opened
    - InProgress
    - Submitted
    - Reviewed
  github_com_HSI-Sandbox-Golang-Team-2025_Team-2_pkg_user_practice_record.UserPracticeRecord:
    properties:
      createdAt:
        example: "2025-10-18T14:42:51.9782263+07:00"
        type: string
        x-order: "01"
      deletedAt:
        example: "null"
        type: string
        x-order: "03"
      id:
        type: integer
        x-order: "00"
      isCorrect:
        type: boolean
      question:
        type: string
      questionAnswerChoice:
        type: string
      questionAnswerChoiceId:
        type: integer
      questionAnswerText:
        type: string
      questionId:
        type: integer
      updatedAt:
        example: "2025-10-18T14:42:51.9782263+07:00"
        type: string
        x-order: "02"
      userPracticeId:
        type: integer
    type: object
  pkg_auth_handler.InvalidLoginResponse:
    properties:
      message:
        example: Invalid Credentials!
        type: string
    type: object
  pkg_auth_handler.InvalidRegisterResponse:
    properties:
      message:
        example: Registration failed!
        type: string
    type: object
  pkg_auth_handler.LoginBody:
    properties:
      nip:
        example: ARN-2402001
        type: string
      password:
        example: "123"
        type: string
    type: object
  pkg_auth_handler.RegisterBody:
    properties:
      name:
        example: Teguh
        type: string
      nip:
        example: ARN-2402001
        type: string
      password:
        example: "123"
        type: string
    type: object
  pkg_auth_handler.SuccessLoginData:
    properties:
      token:
        example: eyJhbGciOiJIUz..
        type: string
    type: object
  pkg_auth_handler.SuccessLoginResponse:
    properties:
      data:
        $ref: '#/definitions/pkg_auth_handler.SuccessLoginData'
      message:
        example: Login success!
        type: string
    type: object
  pkg_auth_handler.SuccessRegisterData:
    properties:
      token:
        example: eyJhbGciOiJIUz..
        type: string
    type: object
  pkg_auth_handler.SuccessRegisterResponse:
    properties:
      data:
        $ref: '#/definitions/pkg_auth_handler.SuccessRegisterData'
      message:
        example: Registration success!
        type: string
    type: object
  pkg_content_handler.GetContentSuccessResponse:
    properties:
      data:
        $ref: '#/definitions/github_com_HSI-Sandbox-Golang-Team-2025_Team-2_pkg_content.Content'
      message:
        example: Get content success!
        type: string
    type: object
  pkg_content_handler.GetContentsSuccessResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/github_com_HSI-Sandbox-Golang-Team-2025_Team-2_pkg_content.Content'
        type: array
      message:
        example: Get content success!
        type: string
    type: object
  pkg_practice_handler.AnswerChoice:
    properties:
      answer:
        example: Benar
        type: string
    type: object
  pkg_practice_handler.Content:
    properties:
      body:
        example: Latihan ini anda akan menguji kemampuan React anda
        type: string
        x-order: "06"
      createdAt:
        example: "2025-10-18T14:42:51.9782263+07:00"
        type: string
        x-order: "01"
      deletedAt:
        example: "null"
        type: string
        x-order: "03"
      id:
        type: integer
        x-order: "00"
      isCompleted:
        example: false
        type: boolean
        x-order: "10"
      order:
        example: 1
        type: integer
        x-order: "08"
      questions:
        items:
          $ref: '#/definitions/github_com_HSI-Sandbox-Golang-Team-2025_Team-2_pkg_question.Question'
        type: array
        x-order: "09"
      title:
        example: Latihan 2
        type: string
        x-order: "05"
      trackId:
        example: 1
        type: integer
        x-order: "04"
      type:
        allOf:
        - $ref: '#/definitions/github_com_HSI-Sandbox-Golang-Team-2025_Team-2_pkg_content.ContentType'
        example: practice
        x-order: "07"
      updatedAt:
        example: "2025-10-18T14:42:51.9782263+07:00"
        type: string
        x-order: "02"
      userPractices:
        example: "null"
        type: string
        x-order:11: true
    type: object
  pkg_practice_handler.CreatePracticeBody:
    properties:
      body:
        example: Latihan ini anda akan menguji kemampuan React anda
        type: string
      questions:
        items:
          $ref: '#/definitions/pkg_practice_handler.Question'
        type: array
      title:
        example: Latihan 2
        type: string
      trackId:
        example: 1
        type: integer
    type: object
  pkg_practice_handler.CreatePracticeErrorResponse:
    properties:
      message:
        example: '[Error message]'
        type: string
    type: object
  pkg_practice_handler.CreatePracticeSuccessResponse:
    properties:
      data:
        $ref: '#/definitions/pkg_practice_handler.Content'
      message:
        example: Create practice content success!
        type: string
    type: object
  pkg_practice_handler.Question:
    properties:
      answerChoices:
        items:
          $ref: '#/definitions/pkg_practice_handler.AnswerChoice'
        type: array
      question:
        example: Apakah 1 + 1 = 2
        type: string
    type: object
host: localhost:3000
info:
  contact: {}
  description: Learning Platform API Documentations
  title: Learning Platform
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Authenticate user with static credentials and return JWT token
      parameters:
      - description: Login credentials
        in: body
        name: credentials
        required: true
        schema:
          $ref: '#/definitions/pkg_auth_handler.LoginBody'
      produces:
      - application/json
      responses:
        "200":
          description: Login success!
          schema:
            $ref: '#/definitions/pkg_auth_handler.SuccessLoginResponse'
        "400":
          description: Invalid credentials!
          schema:
            $ref: '#/definitions/pkg_auth_handler.InvalidLoginResponse'
      summary: User login
      tags:
      - Authentication
  /auth/register:
    post:
      consumes:
      - application/json
      description: Register a user and return a JWT token
      parameters:
      - description: New user data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/pkg_auth_handler.RegisterBody'
      produces:
      - application/json
      responses:
        "200":
          description: Registration success!
          schema:
            $ref: '#/definitions/pkg_auth_handler.SuccessRegisterResponse'
        "400":
          description: '[Error message]'
          schema:
            $ref: '#/definitions/pkg_auth_handler.InvalidRegisterResponse'
      summary: User register
      tags:
      - Authentication
  /contents:
    get:
      consumes:
      - application/json
      description: Get learning contents (materials, practices and projects)
      parameters:
      - description: track.id
        example: "1"
        in: query
        name: trackId
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Get contents success!
          schema:
            $ref: '#/definitions/pkg_content_handler.GetContentsSuccessResponse'
      summary: Get learning contents
      tags:
      - Contents
  /contents/{id}:
    get:
      consumes:
      - application/json
      description: Get learning content (materials, practices and projects)
      parameters:
      - description: content.id
        example: 1
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Get content success!
          schema:
            $ref: '#/definitions/pkg_content_handler.GetContentSuccessResponse'
      summary: Get learning content
      tags:
      - Contents
  /practices:
    post:
      consumes:
      - application/json
      description: Create a new practice content
      parameters:
      - description: Create practice content data
        in: body
        name: credentials
        required: true
        schema:
          $ref: '#/definitions/pkg_practice_handler.CreatePracticeBody'
      produces:
      - application/json
      responses:
        "201":
          description: Get practice content success!
          schema:
            $ref: '#/definitions/pkg_practice_handler.CreatePracticeSuccessResponse'
        "400":
          description: Error
          schema:
            $ref: '#/definitions/pkg_practice_handler.CreatePracticeErrorResponse'
      summary: Create practice content
      tags:
      - Practice
  /projects:
    post:
      consumes:
      - application/json
      description: Authenticate user with static credentials and return JWT token
      produces:
      - application/json
      responses: {}
      summary: User login
      tags:
      - Backlog
  /user-practices:
    get:
      consumes:
      - application/json
      description: Authenticate user with static credentials and return JWT token
      produces:
      - application/json
      responses: {}
      summary: User login
      tags:
      - Backlog
  /user-practices/:id/review:
    patch:
      consumes:
      - application/json
      description: Authenticate user with static credentials and return JWT token
      produces:
      - application/json
      responses: {}
      summary: User login
      tags:
      - Backlog
  /user-practices/:id/start:
    patch:
      consumes:
      - application/json
      description: Authenticate user with static credentials and return JWT token
      produces:
      - application/json
      responses: {}
      summary: User login
      tags:
      - Backlog
  /user-practices/:id/submit:
    patch:
      consumes:
      - application/json
      description: Authenticate user with static credentials and return JWT token
      produces:
      - application/json
      responses: {}
      summary: User login
      tags:
      - Backlog
  /user-projects:
    get:
      consumes:
      - application/json
      description: Authenticate user with static credentials and return JWT token
      produces:
      - application/json
      responses: {}
      summary: Get user projects
      tags:
      - Backlog
    post:
      consumes:
      - application/json
      description: Authenticate user with static credentials and return JWT token
      produces:
      - application/json
      responses: {}
      summary: Start user project
      tags:
      - Backlog
  /user-projects/:id/review:
    patch:
      consumes:
      - application/json
      description: Authenticate user with static credentials and return JWT token
      produces:
      - application/json
      responses: {}
      summary: Review user projects
      tags:
      - Backlog
  /user-projects/:id/submit:
    patch:
      consumes:
      - application/json
      description: Authenticate user with static credentials and return JWT token
      produces:
      - application/json
      responses: {}
      summary: Submit user project
      tags:
      - Backlog
schemes:
- http
securityDefinitions:
  BearerAuth:
    description: Type "Bearer" followed by a space and JWT token.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
